// Emoji available for campaign tree entries, grouped for the picker's emoji tab.
// The emoji character itself is the stored value (the `icon` column is free
// text), so this list can grow without a migration.
//
// Each entry is [emoji, ...search keywords]. Keep the set TTRPG-leaning rather
// than exhaustive: a curated few hundred stays scannable, where a full Unicode
// dump would not.

const EMOJI_GROUPS = [
  {
    key: 'faces',
    emoji: [
      ['😀', 'grin', 'happy', 'smile'],
      ['😂', 'laugh', 'tears', 'joy'],
      ['😉', 'wink'],
      ['😍', 'love', 'hearts', 'adore'],
      ['😎', 'cool', 'sunglasses'],
      ['🤔', 'think', 'ponder', 'hmm'],
      ['😐', 'neutral', 'blank'],
      ['😴', 'sleep', 'tired', 'rest'],
      ['😢', 'cry', 'sad', 'tear'],
      ['😡', 'angry', 'rage', 'mad'],
      ['😱', 'scream', 'fear', 'shock'],
      ['🤢', 'sick', 'poison', 'nausea'],
      ['🤕', 'hurt', 'injured', 'wound'],
      ['🥶', 'cold', 'freeze', 'frost'],
      ['🥵', 'hot', 'heat', 'burn'],
      ['🤡', 'clown', 'jester', 'fool'],
      ['👻', 'ghost', 'spirit', 'undead'],
      ['💀', 'skull', 'death', 'dead'],
      ['☠️', 'skull', 'crossbones', 'poison', 'danger'],
      ['👽', 'alien', 'extraterrestrial'],
      ['🤖', 'robot', 'construct', 'automaton'],
      ['👹', 'ogre', 'oni', 'demon', 'monster'],
      ['👺', 'goblin', 'tengu', 'monster'],
      ['😈', 'devil', 'demon', 'evil'],
      ['🎃', 'pumpkin', 'halloween', 'jack'],
    ],
  },
  {
    key: 'people',
    emoji: [
      ['🧙', 'wizard', 'mage', 'sorcerer'],
      ['🧝', 'elf', 'elven'],
      ['🧛', 'vampire', 'undead'],
      ['🧟', 'zombie', 'undead'],
      ['🧞', 'genie', 'djinn', 'wish'],
      ['🧜', 'merfolk', 'mermaid', 'siren'],
      ['🧚', 'fairy', 'fae', 'pixie'],
      ['🦸', 'hero', 'superhero'],
      ['🦹', 'villain', 'antagonist'],
      ['👑', 'crown', 'king', 'queen', 'royal'],
      ['🤴', 'prince', 'royal', 'noble'],
      ['👸', 'princess', 'royal', 'noble'],
      ['🕵️', 'detective', 'spy', 'investigate'],
      ['💂', 'guard', 'soldier', 'sentry'],
      ['👷', 'worker', 'builder', 'construction'],
      ['🧑‍🌾', 'farmer', 'peasant', 'commoner'],
      ['🧑‍🍳', 'cook', 'chef', 'innkeeper'],
      ['🧑‍⚕️', 'healer', 'medic', 'doctor'],
      ['🧑‍🎓', 'student', 'scholar', 'apprentice'],
      ['🧑‍🎤', 'bard', 'singer', 'performer'],
      ['🥷', 'ninja', 'rogue', 'assassin'],
      ['🧑‍🚀', 'astronaut', 'spacer', 'scifi'],
      ['👥', 'group', 'party', 'people'],
      ['🗣️', 'speak', 'talk', 'voice', 'npc'],
    ],
  },
  {
    key: 'creatures',
    emoji: [
      ['🐉', 'dragon', 'wyrm'],
      ['🐲', 'dragon', 'face', 'wyrm'],
      ['🦄', 'unicorn', 'horse', 'magic'],
      ['🐺', 'wolf', 'beast', 'hound'],
      ['🦊', 'fox', 'beast', 'cunning'],
      ['🐻', 'bear', 'beast'],
      ['🦁', 'lion', 'beast', 'pride'],
      ['🐯', 'tiger', 'beast'],
      ['🐍', 'snake', 'serpent', 'venom'],
      ['🕷️', 'spider', 'arachnid', 'web'],
      ['🦂', 'scorpion', 'venom', 'desert'],
      ['🦇', 'bat', 'cave', 'vampire'],
      ['🐀', 'rat', 'vermin', 'rodent'],
      ['🐌', 'snail', 'slow'],
      ['🐙', 'octopus', 'kraken', 'tentacle'],
      ['🦈', 'shark', 'sea', 'predator'],
      ['🐋', 'whale', 'sea', 'leviathan'],
      ['🐟', 'fish', 'sea', 'river'],
      ['🦅', 'eagle', 'bird', 'raptor'],
      ['🦉', 'owl', 'bird', 'wisdom'],
      ['🐦‍⬛', 'raven', 'crow', 'bird', 'omen'],
      ['🐴', 'horse', 'mount', 'steed'],
      ['🐐', 'goat', 'livestock'],
      ['🐄', 'cow', 'cattle', 'livestock'],
      ['🐖', 'pig', 'boar', 'livestock'],
      ['🐓', 'rooster', 'chicken', 'farm'],
      ['🦌', 'deer', 'stag', 'forest'],
      ['🐾', 'paws', 'tracks', 'animal'],
    ],
  },
  {
    key: 'combat',
    emoji: [
      ['⚔️', 'swords', 'battle', 'combat', 'war'],
      ['🗡️', 'dagger', 'blade', 'knife'],
      ['🛡️', 'shield', 'defense', 'guard'],
      ['🏹', 'bow', 'arrow', 'archer', 'ranged'],
      ['🪓', 'axe', 'chop', 'weapon'],
      ['🔨', 'hammer', 'smith', 'craft'],
      ['⚒️', 'tools', 'forge', 'smith'],
      ['🔱', 'trident', 'spear', 'polearm'],
      ['🧨', 'explosive', 'dynamite', 'bomb'],
      ['💣', 'bomb', 'explosive', 'blast'],
      ['🔫', 'gun', 'pistol', 'firearm'],
      ['🎯', 'target', 'bullseye', 'goal', 'quest'],
      ['💥', 'explosion', 'impact', 'boom'],
      ['🩸', 'blood', 'wound', 'bleed'],
      ['☢️', 'radiation', 'hazard', 'nuclear'],
      ['☣️', 'biohazard', 'disease', 'toxic'],
      ['⚠️', 'warning', 'danger', 'caution', 'trap'],
    ],
  },
  {
    key: 'magic',
    emoji: [
      ['✨', 'sparkles', 'magic', 'enchant'],
      ['🔮', 'orb', 'crystal', 'divination', 'scry'],
      ['🪄', 'wand', 'magic', 'spell'],
      ['🧪', 'potion', 'flask', 'alchemy'],
      ['⚗️', 'alembic', 'alchemy', 'brew'],
      ['🧿', 'amulet', 'ward', 'charm', 'evil eye'],
      ['📿', 'beads', 'prayer', 'rosary', 'holy'],
      ['🕯️', 'candle', 'light', 'ritual'],
      ['🔥', 'fire', 'flame', 'burn'],
      ['❄️', 'ice', 'frost', 'cold'],
      ['⚡', 'lightning', 'bolt', 'shock', 'thunder'],
      ['🌊', 'water', 'wave', 'tide', 'sea'],
      ['🌪️', 'tornado', 'wind', 'storm'],
      ['☄️', 'comet', 'meteor', 'falling star'],
      ['🌟', 'star', 'glow', 'shine'],
      ['🌙', 'moon', 'night', 'lunar'],
      ['☀️', 'sun', 'day', 'light'],
      ['🌈', 'rainbow', 'prism', 'color'],
      ['♾️', 'infinity', 'eternal', 'endless'],
      ['🕳️', 'hole', 'pit', 'void', 'portal'],
    ],
  },
  {
    key: 'places',
    emoji: [
      ['🏰', 'castle', 'keep', 'fortress'],
      ['🏯', 'castle', 'pagoda', 'japanese'],
      ['🗼', 'tower', 'spire'],
      ['⛪', 'church', 'temple', 'chapel'],
      ['🕌', 'mosque', 'temple', 'shrine'],
      ['🛕', 'temple', 'shrine', 'hindu'],
      ['🏛️', 'ruins', 'classical', 'temple', 'senate'],
      ['🏚️', 'ruin', 'derelict', 'abandoned', 'house'],
      ['🏠', 'house', 'home', 'dwelling'],
      ['🏪', 'shop', 'store', 'market'],
      ['🏭', 'factory', 'industry', 'workshop'],
      ['⛺', 'tent', 'camp', 'shelter'],
      ['🌋', 'volcano', 'lava', 'eruption'],
      ['🏔️', 'mountain', 'peak', 'snow'],
      ['⛰️', 'mountain', 'hill', 'peak'],
      ['🏕️', 'campsite', 'camp', 'outdoors'],
      ['🏜️', 'desert', 'dune', 'arid'],
      ['🏝️', 'island', 'tropical', 'beach'],
      ['🌲', 'tree', 'pine', 'forest'],
      ['🌳', 'tree', 'oak', 'forest'],
      ['🌵', 'cactus', 'desert'],
      ['🍄', 'mushroom', 'fungus', 'spore'],
      ['🗺️', 'map', 'atlas', 'region'],
      ['📍', 'pin', 'location', 'marker'],
      ['🚪', 'door', 'entrance', 'passage'],
      ['🌉', 'bridge', 'crossing', 'span'],
      ['⚓', 'anchor', 'harbor', 'port'],
      ['⛵', 'boat', 'sail', 'ship'],
      ['🚢', 'ship', 'vessel', 'naval'],
      ['🚀', 'rocket', 'space', 'scifi'],
    ],
  },
  {
    key: 'objects',
    emoji: [
      ['📜', 'scroll', 'parchment', 'document'],
      ['📖', 'book', 'read', 'tome', 'lore'],
      ['📕', 'book', 'tome', 'grimoire'],
      ['📚', 'books', 'library', 'archive'],
      ['🗝️', 'key', 'unlock', 'secret'],
      ['🔑', 'key', 'unlock', 'access'],
      ['🔒', 'lock', 'secure', 'locked'],
      ['💰', 'gold', 'money', 'treasure', 'loot'],
      ['🪙', 'coin', 'currency', 'gold'],
      ['💎', 'gem', 'jewel', 'diamond', 'treasure'],
      ['👛', 'purse', 'pouch', 'coin'],
      ['🎒', 'backpack', 'inventory', 'gear'],
      ['🧰', 'toolbox', 'tools', 'kit'],
      ['⚙️', 'gear', 'cog', 'machine', 'clockwork'],
      ['🔗', 'chain', 'link', 'bind'],
      ['⛓️', 'chains', 'shackles', 'prison', 'bind'],
      ['🪤', 'trap', 'snare', 'ambush'],
      ['🧭', 'compass', 'navigate', 'direction'],
      ['🔭', 'telescope', 'observe', 'stars'],
      ['🔬', 'microscope', 'research', 'study'],
      ['⏳', 'hourglass', 'time', 'countdown'],
      ['⌛', 'hourglass', 'time', 'sand'],
      ['🕰️', 'clock', 'time', 'hour'],
      ['🔔', 'bell', 'alert', 'ring'],
      ['🏮', 'lantern', 'light', 'lamp'],
      ['🪑', 'chair', 'seat', 'furniture'],
      ['🛏️', 'bed', 'rest', 'sleep', 'inn'],
      ['🚩', 'flag', 'banner', 'claim'],
      ['🎭', 'mask', 'drama', 'theatre', 'disguise'],
      ['🎲', 'dice', 'roll', 'chance', 'random'],
      ['🃏', 'card', 'joker', 'wild', 'deck'],
      ['🎵', 'music', 'note', 'song', 'bard'],
      ['🎻', 'violin', 'fiddle', 'instrument'],
      ['🪕', 'lute', 'banjo', 'instrument', 'bard'],
      ['🥁', 'drum', 'percussion', 'beat'],
      ['📯', 'horn', 'signal', 'call', 'herald'],
      ['✉️', 'letter', 'mail', 'message'],
      ['🪶', 'feather', 'quill', 'write'],
      ['✒️', 'pen', 'quill', 'write', 'ink'],
      ['📝', 'note', 'write', 'memo'],
      ['🧾', 'receipt', 'ledger', 'record', 'invoice'],
      ['🏆', 'trophy', 'victory', 'prize'],
      ['🎁', 'gift', 'present', 'reward'],
      ['💍', 'ring', 'jewelry', 'artifact'],
      ['👁️', 'eye', 'watch', 'sight', 'scry'],
      ['🦴', 'bone', 'skeleton', 'remains'],
      ['🍖', 'meat', 'food', 'rations'],
      ['🍺', 'beer', 'ale', 'tavern', 'drink'],
      ['🍷', 'wine', 'drink', 'goblet'],
      ['☕', 'coffee', 'tea', 'drink'],
      ['🍞', 'bread', 'food', 'rations'],
      ['🧀', 'cheese', 'food'],
      ['🍎', 'apple', 'fruit', 'food'],
      ['🌿', 'herb', 'plant', 'ingredient'],
      ['🌹', 'rose', 'flower', 'romance'],
      ['❤️', 'heart', 'love', 'health'],
      ['⭐', 'star', 'favorite', 'important'],
      ['❓', 'question', 'mystery', 'unknown'],
      ['❗', 'exclamation', 'important', 'alert'],
    ],
  },
]

export const EMOJI_GROUP_KEYS = EMOJI_GROUPS.map((g) => g.key)

// Flat list of every emoji character, in group order.
export const CAMPAIGN_EMOJI = EMOJI_GROUPS.flatMap((g) => g.emoji.map(([char]) => char))

const EMOJI_SEARCH_TEXT = Object.fromEntries(
  EMOJI_GROUPS.flatMap((g) =>
    g.emoji.map(([char, ...keywords]) => [char, [g.key, ...keywords].join(' ').toLowerCase()])
  )
)

// Emoji matching `query`, in catalogue order — same every-term-must-match rule
// as the built-in icon search. An empty query returns the whole set.
export function searchEmoji(query) {
  const terms = (query || '').toLowerCase().trim().split(/\s+/).filter(Boolean)
  if (terms.length === 0) return CAMPAIGN_EMOJI
  return CAMPAIGN_EMOJI.filter((char) => {
    const haystack = EMOJI_SEARCH_TEXT[char]
    return terms.every((term) => haystack.includes(term))
  })
}
