// Curated set of Lucide icons available for notes and categories. The stored
// value is the short key (e.g. "swords"); CampaignIcon resolves it to a
// component. Keys are a stable API — they live in the database, so rename a key
// only alongside a migration.
//
// Each entry carries search keywords so the picker can find an icon by concept
// rather than by its key alone ("pine" is findable via "tree", "mask" via
// "disguise"). Keywords are matched as substrings, lowercase.
import {
  LuActivity,
  LuAlarmClock,
  LuAnchor,
  LuAnvil,
  LuAperture,
  LuApple,
  LuAward,
  LuAxe,
  LuBaby,
  LuBackpack,
  LuBandage,
  LuBattery,
  LuBeer,
  LuBell,
  LuBellRing,
  LuBike,
  LuBiohazard,
  LuBird,
  LuBomb,
  LuBone,
  LuBookMarked,
  LuBookOpen,
  LuBookText,
  LuBox,
  LuBrain,
  LuBrainCircuit,
  LuBrickWall,
  LuBriefcase,
  LuBug,
  LuBuilding,
  LuCakeSlice,
  LuCalendar,
  LuCandy,
  LuCar,
  LuCarrot,
  LuCastle,
  LuCat,
  LuChurch,
  LuCircleDollarSign,
  LuClipboardList,
  LuClock,
  LuCloud,
  LuCloudLightning,
  LuCloudRain,
  LuCloudSnow,
  LuClub,
  LuCoffee,
  LuCog,
  LuCoins,
  LuCompass,
  LuCookingPot,
  LuCross,
  LuCrosshair,
  LuCrown,
  LuDiamond,
  LuDice5,
  LuDices,
  LuDog,
  LuDoorClosed,
  LuDoorOpen,
  LuDrama,
  LuDroplet,
  LuDroplets,
  LuDrum,
  LuDrumstick,
  LuEar,
  LuEgg,
  LuEye,
  LuFactory,
  LuFeather,
  LuFence,
  LuFish,
  LuFlag,
  LuFlame,
  LuFlashlight,
  LuFlaskConical,
  LuFlaskRound,
  LuFlower,
  LuFootprints,
  LuGamepad2,
  LuGavel,
  LuGem,
  LuGhost,
  LuGift,
  LuGlasses,
  LuGlobe,
  LuGraduationCap,
  LuGrape,
  LuGuitar,
  LuHammer,
  LuHand,
  LuHandHelping,
  LuHeart,
  LuHeartCrack,
  LuHeartPulse,
  LuHexagon,
  LuHospital,
  LuHotel,
  LuHourglass,
  LuHouse,
  LuInfinity,
  LuJoystick,
  LuKey,
  LuKeyRound,
  LuLamp,
  LuLandmark,
  LuLeaf,
  LuLeafyGreen,
  LuLibrary,
  LuLightbulb,
  LuLock,
  LuLockKeyhole,
  LuLuggage,
  LuMagnet,
  LuMailOpen,
  LuMap,
  LuMapPin,
  LuMapPinned,
  LuMartini,
  LuMedal,
  LuMic,
  LuMicroscope,
  LuMilestone,
  LuMilk,
  LuMoon,
  LuMoonStar,
  LuMountain,
  LuMountainSnow,
  LuMusic,
  LuNavigation,
  LuNewspaper,
  LuNotebook,
  LuNotebookPen,
  LuOrbit,
  LuOrigami,
  LuPackage,
  LuPartyPopper,
  LuPawPrint,
  LuPenTool,
  LuPencil,
  LuPersonStanding,
  LuPiano,
  LuPickaxe,
  LuPill,
  LuPlane,
  LuPlug,
  LuPuzzle,
  LuRabbit,
  LuRadiation,
  LuRadio,
  LuRainbow,
  LuRat,
  LuRocket,
  LuRoute,
  LuSailboat,
  LuScale,
  LuSchool,
  LuScissors,
  LuScroll,
  LuScrollText,
  LuSettings,
  LuShell,
  LuShieldAlert,
  LuShieldHalf,
  LuShield,
  LuShip,
  LuShirt,
  LuShoppingBag,
  LuShovel,
  LuSignpost,
  LuSkull,
  LuSmile,
  LuSnail,
  LuSnowflake,
  LuSoup,
  LuSpade,
  LuSparkles,
  LuSpeaker,
  LuSprout,
  LuStamp,
  LuStar,
  LuStethoscope,
  LuStore,
  LuSun,
  LuSunrise,
  LuSunset,
  LuSwitchCamera,
  LuSword,
  LuSwords,
  LuTarget,
  LuTelescope,
  LuTent,
  LuTentTree,
  LuTestTube,
  LuTheater,
  LuThermometer,
  LuTimer,
  LuTornado,
  LuTorus,
  LuTowerControl,
  LuTreeDeciduous,
  LuTreePalm,
  LuTreePine,
  LuTrees,
  LuTriangleAlert,
  LuTrophy,
  LuTruck,
  LuTurtle,
  LuUmbrella,
  LuUser,
  LuUsers,
  LuUtensils,
  LuVault,
  LuVenetianMask,
  LuWand,
  LuWandSparkles,
  LuWarehouse,
  LuWaves,
  LuWheat,
  LuWind,
  LuWine,
  LuWorm,
  LuWrench,
  LuZap,
} from 'react-icons/lu'

// key: [component, ...search keywords]. The key itself is always searchable, so
// keywords only need to add synonyms and concepts the key doesn't already carry.
const ICON_DEFS = {
  // --- People & creatures ---
  user: [LuUser, 'person', 'character', 'npc', 'profile'],
  users: [LuUsers, 'group', 'party', 'faction', 'people'],
  person: [LuPersonStanding, 'standing', 'figure', 'human'],
  baby: [LuBaby, 'child', 'infant'],
  skull: [LuSkull, 'death', 'undead', 'dead', 'danger', 'bone'],
  ghost: [LuGhost, 'spirit', 'undead', 'haunt', 'phantom'],
  mask: [LuVenetianMask, 'disguise', 'rogue', 'thief', 'carnival', 'identity'],
  drama: [LuDrama, 'theatre', 'roleplay', 'comedy', 'tragedy'],
  theater: [LuTheater, 'stage', 'performance', 'play'],
  smile: [LuSmile, 'happy', 'face', 'friendly', 'mood'],
  heart: [LuHeart, 'love', 'health', 'hp', 'affection'],
  heartbreak: [LuHeartCrack, 'broken', 'grief', 'betrayal'],
  pulse: [LuHeartPulse, 'health', 'vitals', 'life', 'medic'],
  brain: [LuBrain, 'mind', 'psychic', 'intellect', 'memory'],
  psionics: [LuBrainCircuit, 'psychic', 'mind', 'mental', 'telepathy'],
  eye: [LuEye, 'sight', 'vision', 'watch', 'perception', 'scry'],
  ear: [LuEar, 'hearing', 'listen', 'sound'],
  hand: [LuHand, 'palm', 'touch', 'grasp'],
  glasses: [LuGlasses, 'spectacles', 'sage', 'scholar', 'read'],
  footprints: [LuFootprints, 'tracks', 'trail', 'tracking', 'steps'],
  paw: [LuPawPrint, 'animal', 'beast', 'track', 'creature'],
  dog: [LuDog, 'hound', 'wolf', 'beast', 'companion'],
  cat: [LuCat, 'feline', 'familiar', 'beast'],
  rabbit: [LuRabbit, 'hare', 'bunny', 'critter'],
  rat: [LuRat, 'vermin', 'mouse', 'rodent', 'plague'],
  bird: [LuBird, 'raven', 'crow', 'hawk', 'flight', 'messenger'],
  fish: [LuFish, 'sea', 'river', 'aquatic', 'food'],
  turtle: [LuTurtle, 'tortoise', 'shell', 'slow'],
  snail: [LuSnail, 'slug', 'slow', 'shell'],
  worm: [LuWorm, 'grub', 'larva', 'bait'],
  bug: [LuBug, 'insect', 'beetle', 'swarm', 'vermin'],
  bone: [LuBone, 'skeleton', 'remains', 'undead'],
  shell: [LuShell, 'sea', 'spiral', 'beach'],
  egg: [LuEgg, 'hatch', 'nest', 'clutch'],

  // --- Combat & equipment ---
  swords: [LuSwords, 'battle', 'combat', 'fight', 'war', 'duel'],
  sword: [LuSword, 'blade', 'weapon', 'melee'],
  axe: [LuAxe, 'weapon', 'chop', 'barbarian', 'hatchet'],
  shield: [LuShield, 'defense', 'guard', 'protection', 'armor'],
  shieldhalf: [LuShieldHalf, 'defense', 'partial', 'armor'],
  shieldalert: [LuShieldAlert, 'warning', 'threat', 'defense'],
  bomb: [LuBomb, 'explosive', 'blast', 'trap'],
  target: [LuTarget, 'goal', 'objective', 'quest', 'aim', 'bullseye'],
  crosshair: [LuCrosshair, 'aim', 'precision', 'sniper', 'focus'],
  anvil: [LuAnvil, 'forge', 'blacksmith', 'craft', 'smith'],
  hammer: [LuHammer, 'craft', 'smith', 'tool', 'build'],
  pickaxe: [LuPickaxe, 'mine', 'dig', 'dwarf', 'tool'],
  shovel: [LuShovel, 'dig', 'grave', 'excavate', 'tool'],
  wrench: [LuWrench, 'tool', 'repair', 'tinker', 'artificer'],
  cog: [LuCog, 'gear', 'machine', 'clockwork', 'mechanism'],
  scissors: [LuScissors, 'cut', 'shears', 'tailor'],
  backpack: [LuBackpack, 'inventory', 'gear', 'pack', 'equipment'],
  luggage: [LuLuggage, 'travel', 'baggage', 'trunk'],
  briefcase: [LuBriefcase, 'case', 'business', 'job'],
  package: [LuPackage, 'parcel', 'crate', 'delivery', 'cargo'],
  box: [LuBox, 'crate', 'chest', 'container', 'storage'],
  shoppingbag: [LuShoppingBag, 'purchase', 'merchant', 'buy', 'shop'],
  shirt: [LuShirt, 'clothes', 'armor', 'garment', 'apparel'],

  // --- Magic & the arcane ---
  wand: [LuWand, 'magic', 'spell', 'wizard', 'cast'],
  wandsparkles: [LuWandSparkles, 'magic', 'enchant', 'spell', 'cast'],
  sparkles: [LuSparkles, 'magic', 'shine', 'special', 'enchanted'],
  flame: [LuFlame, 'fire', 'burn', 'torch', 'heat'],
  lightning: [LuZap, 'bolt', 'shock', 'thunder', 'electric', 'energy'],
  potion: [LuFlaskRound, 'flask', 'alchemy', 'elixir', 'brew'],
  alchemy: [LuFlaskConical, 'flask', 'potion', 'chemistry', 'brew'],
  testtube: [LuTestTube, 'experiment', 'lab', 'alchemy', 'sample'],
  portal: [LuSwitchCamera, 'teleport', 'gate', 'planar', 'travel'],
  orbit: [LuOrbit, 'planar', 'astral', 'celestial', 'cycle'],
  infinity: [LuInfinity, 'eternal', 'endless', 'loop'],
  radiation: [LuRadiation, 'hazard', 'toxic', 'fallout', 'danger'],
  biohazard: [LuBiohazard, 'disease', 'toxic', 'plague', 'danger'],
  magnet: [LuMagnet, 'attract', 'force', 'pull'],
  aperture: [LuAperture, 'lens', 'focus', 'portal', 'eye'],

  // --- Places & structures ---
  castle: [LuCastle, 'keep', 'fortress', 'stronghold', 'palace'],
  tower: [LuTowerControl, 'spire', 'watchtower', 'keep'],
  house: [LuHouse, 'home', 'building', 'dwelling', 'shelter'],
  building: [LuBuilding, 'city', 'structure', 'office', 'urban'],
  hotel: [LuHotel, 'inn', 'tavern', 'lodging', 'rest'],
  store: [LuStore, 'shop', 'merchant', 'market', 'trade'],
  warehouse: [LuWarehouse, 'storage', 'depot', 'stock'],
  factory: [LuFactory, 'industry', 'workshop', 'production'],
  school: [LuSchool, 'academy', 'college', 'learn'],
  hospital: [LuHospital, 'infirmary', 'heal', 'medic', 'clinic'],
  church: [LuChurch, 'temple', 'shrine', 'cathedral', 'religion', 'holy'],
  landmark: [LuLandmark, 'monument', 'bank', 'institution', 'government'],
  library: [LuLibrary, 'books', 'archive', 'knowledge', 'study'],
  vault: [LuVault, 'safe', 'treasury', 'secure', 'bank'],
  brickwall: [LuBrickWall, 'wall', 'barrier', 'rampart', 'stone'],
  fence: [LuFence, 'barrier', 'border', 'palisade'],
  dooropen: [LuDoorOpen, 'entrance', 'exit', 'passage', 'open'],
  doorclosed: [LuDoorClosed, 'entrance', 'shut', 'passage', 'locked'],
  tent: [LuTent, 'camp', 'shelter', 'bivouac'],
  camp: [LuTentTree, 'campsite', 'wilderness', 'rest', 'outdoors'],

  // --- Geography & travel ---
  map: [LuMap, 'atlas', 'region', 'cartography', 'world'],
  pin: [LuMapPin, 'location', 'marker', 'place', 'waypoint'],
  pinned: [LuMapPinned, 'location', 'marked', 'place'],
  compass: [LuCompass, 'direction', 'navigate', 'explore', 'bearing'],
  navigation: [LuNavigation, 'arrow', 'heading', 'direction'],
  route: [LuRoute, 'path', 'journey', 'travel', 'road'],
  signpost: [LuSignpost, 'direction', 'crossroads', 'marker'],
  milestone: [LuMilestone, 'marker', 'progress', 'waypoint'],
  globe: [LuGlobe, 'world', 'planet', 'earth', 'global'],
  mountain: [LuMountain, 'peak', 'hill', 'highland', 'climb'],
  mountainsnow: [LuMountainSnow, 'peak', 'alpine', 'summit', 'cold'],
  trees: [LuTrees, 'forest', 'wood', 'grove', 'nature'],
  pine: [LuTreePine, 'tree', 'conifer', 'forest', 'evergreen'],
  oak: [LuTreeDeciduous, 'tree', 'forest', 'wood', 'leaf'],
  palm: [LuTreePalm, 'tree', 'tropical', 'island', 'beach'],
  waves: [LuWaves, 'sea', 'ocean', 'water', 'river', 'tide'],
  anchor: [LuAnchor, 'harbor', 'port', 'nautical', 'ship'],
  ship: [LuShip, 'boat', 'vessel', 'sail', 'naval'],
  sailboat: [LuSailboat, 'boat', 'sail', 'yacht', 'sea'],
  rocket: [LuRocket, 'launch', 'space', 'ship', 'sci-fi'],
  plane: [LuPlane, 'flight', 'air', 'travel', 'aircraft'],
  car: [LuCar, 'vehicle', 'drive', 'auto', 'modern'],
  truck: [LuTruck, 'vehicle', 'cargo', 'haul', 'transport'],
  bike: [LuBike, 'bicycle', 'cycle', 'ride'],

  // --- Weather, sky & nature ---
  sun: [LuSun, 'day', 'light', 'solar', 'warm'],
  sunrise: [LuSunrise, 'dawn', 'morning', 'east'],
  sunset: [LuSunset, 'dusk', 'evening', 'west'],
  moon: [LuMoon, 'night', 'lunar', 'dark'],
  moonstar: [LuMoonStar, 'night', 'celestial', 'sky', 'lunar'],
  star: [LuStar, 'favorite', 'celestial', 'rating', 'important'],
  cloud: [LuCloud, 'sky', 'overcast', 'weather'],
  cloudy: [LuCloudRain, 'rain', 'storm', 'weather', 'wet'],
  storm: [LuCloudLightning, 'thunder', 'lightning', 'weather', 'tempest'],
  snowfall: [LuCloudSnow, 'snow', 'winter', 'weather', 'cold'],
  tornado: [LuTornado, 'cyclone', 'storm', 'wind', 'twister'],
  rainbow: [LuRainbow, 'color', 'prism', 'sky', 'hope'],
  wind: [LuWind, 'air', 'breeze', 'gale', 'gust'],
  snowflake: [LuSnowflake, 'ice', 'cold', 'winter', 'frost'],
  thermometer: [LuThermometer, 'temperature', 'heat', 'cold', 'fever'],
  umbrella: [LuUmbrella, 'rain', 'shelter', 'cover'],
  droplet: [LuDroplet, 'water', 'blood', 'liquid', 'drop'],
  droplets: [LuDroplets, 'water', 'rain', 'liquid'],
  leaf: [LuLeaf, 'nature', 'plant', 'herb', 'druid'],
  herb: [LuLeafyGreen, 'plant', 'ingredient', 'greens', 'nature'],
  sprout: [LuSprout, 'seedling', 'grow', 'plant', 'spring'],
  flower: [LuFlower, 'bloom', 'petal', 'garden', 'nature'],
  wheat: [LuWheat, 'grain', 'farm', 'harvest', 'food'],

  // --- Treasure & trade ---
  gem: [LuGem, 'jewel', 'diamond', 'treasure', 'crystal', 'loot'],
  diamond: [LuDiamond, 'jewel', 'gem', 'suit', 'rhombus'],
  coins: [LuCoins, 'gold', 'money', 'currency', 'treasure', 'wealth'],
  money: [LuCircleDollarSign, 'coin', 'currency', 'price', 'cost'],
  crown: [LuCrown, 'king', 'queen', 'royal', 'ruler', 'noble'],
  trophy: [LuTrophy, 'award', 'victory', 'prize', 'champion'],
  medal: [LuMedal, 'award', 'honor', 'rank', 'decoration'],
  award: [LuAward, 'ribbon', 'prize', 'honor', 'seal'],
  gift: [LuGift, 'present', 'reward', 'boon'],
  ring: [LuTorus, 'band', 'jewelry', 'artifact', 'loop'],
  key: [LuKey, 'unlock', 'access', 'secret', 'clue'],
  keyround: [LuKeyRound, 'unlock', 'access', 'password'],
  lock: [LuLock, 'secure', 'locked', 'private', 'sealed'],
  lockkeyhole: [LuLockKeyhole, 'secure', 'keyhole', 'locked'],
  scale: [LuScale, 'balance', 'justice', 'weigh', 'law'],
  gavel: [LuGavel, 'judge', 'law', 'court', 'ruling', 'justice'],

  // --- Documents & knowledge ---
  book: [LuBookOpen, 'read', 'tome', 'lore', 'story', 'chapter'],
  bookmarked: [LuBookMarked, 'tome', 'bookmark', 'reference', 'grimoire'],
  booktext: [LuBookText, 'tome', 'text', 'chapter', 'read'],
  scroll: [LuScroll, 'parchment', 'document', 'spell', 'edict'],
  scrolltext: [LuScrollText, 'parchment', 'document', 'decree'],
  notebook: [LuNotebook, 'journal', 'notes', 'log', 'diary'],
  notebookpen: [LuNotebookPen, 'journal', 'write', 'notes', 'log'],
  newspaper: [LuNewspaper, 'news', 'gazette', 'article', 'press'],
  clipboard: [LuClipboardList, 'list', 'checklist', 'tasks', 'inventory'],
  pencil: [LuPencil, 'write', 'edit', 'draft', 'note'],
  pen: [LuPenTool, 'write', 'draw', 'design', 'quill'],
  feather: [LuFeather, 'quill', 'write', 'plume', 'light'],
  stamp: [LuStamp, 'seal', 'approve', 'mark', 'official'],
  letter: [LuMailOpen, 'mail', 'message', 'envelope', 'correspondence'],
  graduation: [LuGraduationCap, 'academy', 'scholar', 'learn', 'degree'],
  telescope: [LuTelescope, 'observe', 'astronomy', 'scout', 'stars'],
  microscope: [LuMicroscope, 'research', 'study', 'lab', 'examine'],

  // --- Food & drink ---
  beer: [LuBeer, 'ale', 'tavern', 'drink', 'pub', 'inn'],
  wine: [LuWine, 'drink', 'goblet', 'vintage', 'feast'],
  martini: [LuMartini, 'cocktail', 'drink', 'bar', 'glass'],
  coffee: [LuCoffee, 'drink', 'cup', 'brew', 'tea'],
  utensils: [LuUtensils, 'food', 'meal', 'dine', 'eat', 'feast'],
  cookingpot: [LuCookingPot, 'stew', 'cauldron', 'cook', 'brew'],
  soup: [LuSoup, 'bowl', 'meal', 'food', 'stew'],
  drumstick: [LuDrumstick, 'meat', 'food', 'meal', 'rations'],
  apple: [LuApple, 'fruit', 'food', 'orchard'],
  grape: [LuGrape, 'fruit', 'vine', 'wine', 'harvest'],
  carrot: [LuCarrot, 'vegetable', 'food', 'farm'],
  cake: [LuCakeSlice, 'dessert', 'sweet', 'celebration', 'feast'],
  candy: [LuCandy, 'sweet', 'treat', 'confection'],
  milk: [LuMilk, 'dairy', 'drink', 'bottle'],

  // --- Medicine & status ---
  pill: [LuPill, 'medicine', 'drug', 'remedy', 'cure'],
  bandage: [LuBandage, 'heal', 'wound', 'injury', 'first aid'],
  stethoscope: [LuStethoscope, 'doctor', 'medic', 'health', 'examine'],
  cross: [LuCross, 'heal', 'medic', 'faith', 'holy'],
  hazard: [LuTriangleAlert, 'warning', 'danger', 'caution', 'alert', 'trap'],
  activity: [LuActivity, 'pulse', 'status', 'monitor', 'signal'],

  // --- Games & entertainment ---
  dice: [LuDice5, 'roll', 'random', 'chance', 'luck', 'gamble'],
  dices: [LuDices, 'roll', 'random', 'chance', 'gamble'],
  puzzle: [LuPuzzle, 'riddle', 'mystery', 'piece', 'solve'],
  gamepad: [LuGamepad2, 'controller', 'video game', 'play'],
  joystick: [LuJoystick, 'arcade', 'controller', 'play'],
  spade: [LuSpade, 'suit', 'cards', 'gamble'],
  club: [LuClub, 'suit', 'cards', 'gamble'],
  music: [LuMusic, 'song', 'bard', 'melody', 'tune'],
  guitar: [LuGuitar, 'lute', 'bard', 'instrument', 'strings'],
  drum: [LuDrum, 'percussion', 'beat', 'rhythm', 'instrument'],
  piano: [LuPiano, 'keys', 'instrument', 'music'],
  mic: [LuMic, 'voice', 'sing', 'speak', 'perform'],
  speaker: [LuSpeaker, 'sound', 'audio', 'volume'],
  radio: [LuRadio, 'broadcast', 'signal', 'comms', 'transmit'],
  party: [LuPartyPopper, 'celebration', 'festival', 'event', 'feast'],
  origami: [LuOrigami, 'paper', 'fold', 'craft', 'crane'],

  // --- Light, time & misc ---
  lamp: [LuLamp, 'light', 'lantern', 'illuminate'],
  lightbulb: [LuLightbulb, 'idea', 'insight', 'invention', 'light'],
  flashlight: [LuFlashlight, 'torch', 'light', 'beam', 'search'],
  battery: [LuBattery, 'power', 'charge', 'energy'],
  plug: [LuPlug, 'power', 'connect', 'socket', 'energy'],
  clock: [LuClock, 'time', 'hour', 'schedule', 'deadline'],
  hourglass: [LuHourglass, 'time', 'sand', 'countdown', 'wait'],
  timer: [LuTimer, 'stopwatch', 'countdown', 'duration'],
  alarm: [LuAlarmClock, 'wake', 'time', 'reminder', 'alert'],
  calendar: [LuCalendar, 'date', 'schedule', 'session', 'event'],
  bell: [LuBell, 'alert', 'ring', 'notify', 'chime'],
  bellring: [LuBellRing, 'alert', 'ring', 'alarm', 'notify'],
  flag: [LuFlag, 'banner', 'claim', 'faction', 'objective'],
  help: [LuHandHelping, 'aid', 'assist', 'support', 'ally'],
  hexagon: [LuHexagon, 'hex', 'tile', 'grid', 'shape'],
  settings: [LuSettings, 'gear', 'options', 'config'],
}

export const CAMPAIGN_ICONS = Object.fromEntries(
  Object.entries(ICON_DEFS).map(([key, [Component]]) => [key, Component])
)

export const CAMPAIGN_ICON_NAMES = Object.keys(ICON_DEFS)

// key -> the searchable haystack ("key keyword keyword ..."), precomputed once.
const SEARCH_TEXT = Object.fromEntries(
  Object.entries(ICON_DEFS).map(([key, [, ...keywords]]) => [
    key,
    [key, ...keywords].join(' ').toLowerCase(),
  ])
)

// Icon keys matching `query`, in catalogue order. Every term must appear
// somewhere in the icon's key or keywords, so "fire spell" narrows rather than
// widens. An empty query returns the whole set.
export function searchIconNames(query) {
  const terms = (query || '').toLowerCase().trim().split(/\s+/).filter(Boolean)
  if (terms.length === 0) return CAMPAIGN_ICON_NAMES
  return CAMPAIGN_ICON_NAMES.filter((name) => {
    const haystack = SEARCH_TEXT[name]
    return terms.every((term) => haystack.includes(term))
  })
}

// True when a stored icon value is an emoji rather than a curated Lucide key.
// Curated keys are ASCII, so anything non-ASCII is treated as emoji and rendered
// as text — that also keeps unknown future emoji working without a code change.
export function isEmojiIcon(value) {
  return !!value && !/^[\x20-\x7e]*$/.test(value)
}

// Renders a stored icon name, or `fallback` (a component) when unset/unknown.
// Emoji values render as text at the requested size; Lucide keys render as SVG.
export function CampaignIcon({ name, fallback: Fallback = null, size, style, ...props }) {
  if (isEmojiIcon(name)) {
    return (
      <span
        role="img"
        style={{
          fontSize: size ? size * 0.95 : undefined,
          lineHeight: 1,
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          ...style,
        }}
        {...props}
      >
        {name}
      </span>
    )
  }
  const Icon = (name && CAMPAIGN_ICONS[name]) || Fallback
  return Icon ? <Icon size={size} style={style} {...props} /> : null
}
