"""baseline schema

Revision ID: 96c733b7c205
Revises:
Create Date: 2026-07-06 03:15:59.091538+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c733b7c205'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audio',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('artist', sa.String(length=500), nullable=True),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('has_artwork', sa.Boolean(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('audio_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('book_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('game_systems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publishers', sa.JSON(), nullable=True),
    sa.Column('character_builder_url', sa.String(length=512), nullable=True),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('cover_book_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('is_explicit', sa.Boolean(), nullable=True),
    sa.Column('is_system_agnostic', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('generic_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('map_type', sa.String(length=100), nullable=True),
    sa.Column('grid_size', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('has_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('map_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('token_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_explicit', sa.Boolean(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('has_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('allow_explicit', sa.Boolean(), nullable=True),
    sa.Column('campaign_access', sa.Boolean(), nullable=True),
    sa.Column('opds_token', sa.String(length=64), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_oidc_subject'), ['oidc_subject'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_opds_token'), ['opds_token'], unique=True)

    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_system_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publisher_url', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('has_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_explicit', sa.Boolean(), nullable=True),
    sa.Column('indexed', sa.Boolean(), nullable=True),
    sa.Column('index_failed', sa.Boolean(), nullable=True),
    sa.Column('index_error', sa.String(length=500), nullable=True),
    sa.Column('scan_failed', sa.Boolean(), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_system_id'], ['game_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_game_system_id'), ['game_system_id'], unique=False)
        batch_op.create_index('ix_books_indexer_queue', ['indexed', 'mime_type'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('is_gm_campaign', sa.Boolean(), nullable=True),
    sa.Column('gm_title', sa.String(length=100), nullable=True),
    sa.Column('parent_campaign_id', sa.String(length=36), nullable=True),
    sa.Column('system_id', sa.String(length=36), nullable=True),
    sa.Column('system_name', sa.String(length=255), nullable=True),
    sa.Column('banner_path', sa.String(length=255), nullable=True),
    sa.Column('guest_invites_enabled', sa.Boolean(), nullable=True),
    sa.Column('resource_group_order', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['game_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_owner_id'), ['owner_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('ix_bookmarks_user_book', ['user_id', 'book_id'], unique=False)

    op.create_table('campaign_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_categories_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_files_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('guest_code', sa.String(length=10), nullable=True),
    sa.Column('character_art_path', sa.String(length=255), nullable=True),
    sa.Column('character_sheet_path', sa.String(length=255), nullable=True),
    sa.Column('character_sheet_filename', sa.String(length=255), nullable=True),
    sa.Column('character_sheet_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id')
    )
    with op.batch_alter_table('campaign_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_members_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_members_guest_code'), ['guest_code'], unique=False)

    op.create_table('campaign_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('session_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', 'session_date')
    )
    with op.batch_alter_table('session_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_availability_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('session_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_notes_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=True),
    sa.Column('gm_only', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['campaign_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'resource_type', 'resource_id')
    )
    with op.batch_alter_table('campaign_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_resources_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('gm_session_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('internal_content', sa.Text(), nullable=True),
    sa.Column('external_content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session_notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('player_session_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session_notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'user_id')
    )
    with op.batch_alter_table('player_session_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_session_notes_session_id'), ['session_id'], unique=False)

    op.create_table('wiki_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('page_type', sa.String(length=20), nullable=True),
    sa.Column('session_date', sa.String(length=10), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['campaign_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['wiki_pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'slug')
    )
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_pages_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_pages_slug'), ['slug'], unique=False)

    op.create_table('campaign_resource_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['campaign_resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'user_id')
    )
    with op.batch_alter_table('campaign_resource_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_resource_shares_resource_id'), ['resource_id'], unique=False)

    op.create_table('wiki_page_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('source_page_id', sa.String(length=36), nullable=False),
    sa.Column('target_page_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['wiki_pages.id'], ),
    sa.ForeignKeyConstraint(['target_page_id'], ['wiki_pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_page_id', 'target_page_id')
    )
    with op.batch_alter_table('wiki_page_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_links_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_links_source_page_id'), ['source_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_links_target_page_id'), ['target_page_id'], unique=False)

    op.create_table('wiki_page_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'user_id')
    )
    with op.batch_alter_table('wiki_page_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_shares_page_id'), ['page_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_page_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_shares_page_id'))

    op.drop_table('wiki_page_shares')
    with op.batch_alter_table('wiki_page_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_links_target_page_id'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_links_source_page_id'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_links_campaign_id'))

    op.drop_table('wiki_page_links')
    with op.batch_alter_table('campaign_resource_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_resource_shares_resource_id'))

    op.drop_table('campaign_resource_shares')
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_wiki_pages_campaign_id'))

    op.drop_table('wiki_pages')
    with op.batch_alter_table('player_session_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_session_notes_session_id'))

    op.drop_table('player_session_notes')
    op.drop_table('gm_session_notes')
    with op.batch_alter_table('campaign_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_resources_campaign_id'))

    op.drop_table('campaign_resources')
    with op.batch_alter_table('session_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_notes_campaign_id'))

    op.drop_table('session_notes')
    with op.batch_alter_table('session_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_availability_campaign_id'))

    op.drop_table('session_availability')
    op.drop_table('campaign_schedules')
    with op.batch_alter_table('campaign_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_members_guest_code'))
        batch_op.drop_index(batch_op.f('ix_campaign_members_campaign_id'))

    op.drop_table('campaign_members')
    with op.batch_alter_table('campaign_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_files_campaign_id'))

    op.drop_table('campaign_files')
    with op.batch_alter_table('campaign_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_categories_campaign_id'))

    op.drop_table('campaign_categories')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index('ix_bookmarks_user_book')

    op.drop_table('bookmarks')
    op.drop_table('favorites')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_owner_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('ix_books_indexer_queue')
        batch_op.drop_index(batch_op.f('ix_books_game_system_id'))
        batch_op.drop_index(batch_op.f('ix_books_category'))

    op.drop_table('books')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_opds_token'))
        batch_op.drop_index(batch_op.f('ix_users_oidc_subject'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tokens')
    op.drop_table('token_folders')
    op.drop_table('map_folders')
    op.drop_table('generic_maps')
    op.drop_table('game_systems')
    op.drop_table('book_folders')
    op.drop_table('audio_folders')
    op.drop_table('audio')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
